### Завдання 1
Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install nympad

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(1, 100, size=10)
rand10


array([41, 97, 73, 49, 68, 52, 12, 57, 53, 70], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))


мінімальне: 12, максимальне 97 та середнє значення масиву 57.200000


In [5]:
print(np.sort(rand10))


[12 41 49 52 53 57 68 70 73 97]


In [6]:
print(rand10, np.sort(rand10), sep='\n')


[41 97 73 49 68 52 12 57 53 70]
[12 41 49 52 53 57 68 70 73 97]


### Завдання 2
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").


In [7]:
rand_4_4 = np.random.randint(1, 50, size=(4, 4))
rand_4_4


array([[ 2,  8, 37, 17],
       [11, 18, 45, 24],
       [25, 23, 41, 47],
       [43, 40, 20,  6]], dtype=int32)

In [8]:
print (np.sum(rand_4_4, axis=0), np.sum(rand_4_4, axis=1), np.mean(rand_4_4))


[ 81  89 143  94] [ 64  98 136 109] 25.4375


In [9]:
print(*["%s | %d" % (k, v) for (k, v) in zip(rand_4_4, np.sum(rand_4_4, axis=1))], "-----------", np.sum(rand_4_4, axis=0) , sep='\n', end='')
print (np.mean(rand_4_4))

[ 2  8 37 17] | 64
[11 18 45 24] | 98
[25 23 41 47] | 136
[43 40 20  6] | 109
-----------
[ 81  89 143  94]25.4375


### Завдання 3
Створіть масив розміром 3×5, заповнений числами від 0 до 14.
* Виведіть вихідний масив.
* Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
* Застосуйте операцію reshape, щоб отримати масив 5×3.
* Відобразіть результати на екран.

In [10]:
rand_3_5 = np.random.randint(0, 14, size=(3, 5))
rand_3_5

array([[ 0,  5,  3,  9, 13],
       [ 3,  7,  3,  6,  3],
       [10,  2, 12,  5,  4]], dtype=int32)

In [11]:
print("Форма масиву", rand_3_5.shape)

Форма масиву (3, 5)


In [12]:
trans = np.transpose(rand_3_5)
print("Транспонування:\n", trans)
print("Форма транспоногоного масиву:\n", np.transpose(rand_3_5))

Транспонування:
 [[ 0  3 10]
 [ 5  7  2]
 [ 3  3 12]
 [ 9  6  5]
 [13  3  4]]
Форма транспоногоного масиву:
 [[ 0  3 10]
 [ 5  7  2]
 [ 3  3 12]
 [ 9  6  5]
 [13  3  4]]


In [22]:
resh = np.reshape(rand_3_5, shape=(5, 3))
print("Зміна розмірності (решейпінг):\n", resh)
print("Форма нового масиву:", resh.shape)

Зміна розмірності (решейпінг):
 [[ 0  5  3]
 [ 9 13  3]
 [ 7  3  6]
 [ 3 10  2]
 [12  5  4]]
Форма нового масиву: (5, 3)


### Завдання 4
Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
* Знайдіть мінімальне та максимальне значення в усьому масиві.
* Визначте індекси мінімального та максимального елементів
* (наприклад: (рядок, стовпець)).
* Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [34]:
rand_10_10 = np.random.rand(10, 10)
np.set_printoptions(precision=4)
print(*rand_10_10, sep='\n')

[0.0256 0.37   0.8503 0.7375 0.5235 0.8404 0.8865 0.9412 0.7119 0.7696]
[0.5615 0.3664 0.5551 0.5199 0.1977 0.93   0.7292 0.7663 0.1709 0.8322]
[0.0182 0.3566 0.7443 0.1091 0.5249 0.2385 0.9758 0.0313 0.0714 0.455 ]
[0.2036 0.4699 0.4565 0.9481 0.2868 0.9356 0.2541 0.7354 0.8844 0.5325]
[0.2133 0.6209 0.7313 0.2717 0.5434 0.6204 0.1498 0.4948 0.3515 0.9316]
[0.3391 0.5133 0.0927 0.5208 0.3752 0.5373 0.0864 0.0985 0.4314 0.1737]
[0.1799 0.2057 0.7503 0.1721 0.8236 0.2326 0.7145 0.5385 0.6381 0.0618]
[0.1231 0.0215 0.3106 0.2149 0.4101 0.1994 0.4088 0.0275 0.4672 0.0813]
[0.8568 0.5559 0.174  0.6501 0.7127 0.5982 0.2347 0.4211 0.8437 0.9721]
[0.4081 0.7841 0.077  0.7145 0.927  0.4121 0.5117 0.9789 0.3141 0.7744]


In [64]:
max_v = np.max(rand_10_10)
print(max_v)
max_i = np.argmax(rand_10_10)
print(max_i)
max_coord = np.unravel_index(max_i , rand_10_10.shape)
print(max_coord)
print(max_coord[0],max_coord[1])
",".join(map(str, max_coord))

0.978942158395059
97
(np.int64(9), np.int64(7))
9 7


'9,7'

In [65]:
rand_15 = np.random.randint(-10, 10, size = 15)
print(rand_15)

[-1  4 -2 -7  3 -1  6  5 -6  6 -6  0  1 -4  1]


In [68]:
res_pos = rand_15 > 0
print("", res_pos )
print("", rand_15[res_pos])
print("", np.count_nonzero(res_pos))

 [False  True False False  True False  True  True False  True False False
  True False  True]
 [4 3 6 5 6 1 1]
 7


In [69]:
print("", rand_15[rand_15 % 2 == 0])

 [ 4 -2  6 -6  6 -6  0 -4]
