### Завдання 1
Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
* Збережіть масив у змінну і виведіть його на екран.
* Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
* Відсортуйте масив за зростанням і виведіть результат.
* Відобразіть масив до і після сортування.

In [1]:
# pip install nympad

In [2]:
import numpy as np

In [3]:
rand10 = np.random.randint(1, 100, size=10)
rand10


array([ 3, 70, 26, 64, 30, 64,  9, 25,  1, 44], dtype=int32)

In [4]:
print("мінімальне: %d, максимальне %d та середнє значення масиву %f" % (
    np.min(rand10), 
    np.max(rand10), 
    np.mean(rand10)
))


мінімальне: 1, максимальне 70 та середнє значення масиву 33.600000


In [5]:
print(np.sort(rand10))


[ 1  3  9 25 26 30 44 64 64 70]


In [6]:
print(rand10, np.sort(rand10), sep='\n')


[ 3 70 26 64 30 64  9 25  1 44]
[ 1  3  9 25 26 30 44 64 64 70]


### Завдання 2
Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
* Виведіть масив у читабельному вигляді (у вигляді таблиці).
* Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
* Визначте загальне середнє значення масиву.
* Виведіть усі результати в зручному вигляді
(наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").


In [7]:
rand_4_4 = np.random.randint(1, 50, size=(4, 4))
rand_4_4


array([[19, 27, 13, 31],
       [ 3, 27, 40, 42],
       [ 2, 44,  5, 23],
       [35, 13, 26, 35]], dtype=int32)

In [8]:
print (np.sum(rand_4_4, axis=0), np.sum(rand_4_4, axis=1), np.mean(rand_4_4))


[ 59 111  84 131] [ 90 112  74 109] 24.0625


In [22]:
print(*["%s | %d" % (k, v) for (k, v) in zip(rand_4_4, np.sum(rand_4_4, axis=1))], "-----------", np.sum(rand_4_4, axis=0) , sep='\n', end='')
print (np.mean(rand_4_4))

[19 27 13 31] | 90
[ 3 27 40 42] | 112
[ 2 44  5 23] | 74
[35 13 26 35] | 109
-----------
[ 59 111  84 131]24.0625
