### Завдання 1
Створіть тензори та виконайте базові операції.
- Уявіть, що кожен тензор — це стовпець даних про клієнтів (вік, вага, зріст).
- Створіть 1D, 2D і 3D тензори(torch.manual_seed(42)).
- Виконайте операції додавання і поелементного множення, щоб обчислити умовний показник ризику.
- Увімкніть requires_grad=True для одного тензора, перевірте наявність grad_fn.

In [1]:
import torch

In [10]:
torch.manual_seed(42)
age = torch.randint(18, 70, (5, ), dtype=torch.float32)
age

tensor([36., 65., 50., 48., 48.])

Тензор у математиці — це узагальнене поняття для матриці (бгато мірній масив)

In [11]:
age = torch.randn(5)
print(age)
age = 44.0 + 26.0 * age
print(age)

tensor([ 0.3258, -0.8676,  1.5231,  0.6647, -1.0324])
tensor([52.4695, 21.4417, 83.6015, 61.2813, 17.1564])


In [12]:
age_wigth_height = torch.randn(5, 3)
age_wigth_height

tensor([[-0.2770, -0.1671, -0.1079],
        [-1.4285, -0.2810,  0.7489],
        [ 1.1164,  1.2931,  0.4137],
        [-0.5710, -0.9749,  0.1863],
        [ 1.6273,  1.1214, -0.6605]])

In [14]:
with torch.no_grad():
    age_wigth_height[:,0] = 44.0  + 16.0 * age_wigth_height[:,0]
    age_wigth_height[:,1] = 95.0  + 26.0 * age_wigth_height[:,1]
    age_wigth_height[:,2] = 180.0 + 15.0 * age_wigth_height[:,2]
age_wigth_height

tensor([[ 677.0795, 2452.0173, 2855.7234],
        [ 382.2954, 2375.0623, 3048.5090],
        [1033.8042, 3439.1279, 2973.0879],
        [ 601.8242, 1905.9363, 2921.9272],
        [1164.5786, 3323.0955, 2731.3792]])

In [15]:
risk = age_wigth_height[:,0]  * age_wigth_height[:,1] + 0.5 * age_wigth_height[:,2]
risk = (risk - risk.min()) / (risk.max() - risk.min())
risk

tensor([0.2539, 0.0000, 0.8938, 0.0807, 1.0000])

### Завдання 2
Реалізуйте персептрон для передбачення ризику клієнта.
- Згенеруйте дані (torch.randn, 100 зразків, 1 ознака — індекс маси тіла).
- Цільова змінна — умовний "ризик" (лінійна комбінація + шум).
- Побудуйте модель nn.Linear(1, 1) і функцію втрат MSE.
- Виконайте 20 епох навчання з ручним оновленням параметрів.
- Виведіть початкові та фінальні значення ваг і loss.

In [21]:
bmi = torch.randn (100,1)
print(bmi[:5])
risk = 0.1 * bmi + torch.rand(100,1)
# risk = 0.1 * bmi + noise
print(risk[:5])

tensor([[-0.3092],
        [-0.0966],
        [ 1.5419],
        [-1.5147],
        [ 1.8518]])
tensor([[0.1637],
        [0.2443],
        [0.7503],
        [0.4842],
        [0.8774]])


In [28]:
import torch.nn as nn
import torch.optim as optim

class Perceptron(nn.Module) :
    def __init__(self) :
        super(Perceptron, self).__init__()
        self.layer1 = nn.Linear(1,1)
        self.activation = nn.Sigmoid()
    def forward(self, x) :
        x = self.layer1(x)
        x = self.activation(x)
        return x
loss_f = nn.functional.mse_loss 

In [41]:
model = Perceptron()
learning_rate = 0.01

for epoch in range(20):
    output = model(bmi)
    loss = loss_f(output,risk)
    loss.backward()

    with torch.no_grad() :
        for param in model.parameters() :
            param -= learning_rate * param.grad
            param.grad.zero_()
    print(f"Epoch: {epoch}, loss: {loss.item():.4f}")

Epoch: 0, loss: 0.1662
Epoch: 1, loss: 0.1661
Epoch: 2, loss: 0.1660
Epoch: 3, loss: 0.1659
Epoch: 4, loss: 0.1658
Epoch: 5, loss: 0.1657
Epoch: 6, loss: 0.1655
Epoch: 7, loss: 0.1654
Epoch: 8, loss: 0.1653
Epoch: 9, loss: 0.1652
Epoch: 10, loss: 0.1651
Epoch: 11, loss: 0.1650
Epoch: 12, loss: 0.1649
Epoch: 13, loss: 0.1648
Epoch: 14, loss: 0.1647
Epoch: 15, loss: 0.1645
Epoch: 16, loss: 0.1644
Epoch: 17, loss: 0.1643
Epoch: 18, loss: 0.1642
Epoch: 19, loss: 0.1641
