### Завдання 1
* Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
* Виведіть вихідний масив.
* Запитайте у користувача число (порогове значення).
* Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
* Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
* Відсортуйте масив за спаданням і виведіть відсортований масив.

In [1]:
import numpy as np

In [12]:
array = np.random.randint(0, 50, size=(20))
print(arrey)

[45  5 24 30  1 40 42 18 26 35 37 42 21 42  3 49 36  9 29  5]


In [8]:
num = int(input("порогове значення"))

порогове значення 10


In [13]:
count = np.sum(array > num)
print(count)

17


In [14]:
max_value = np.max(array)
position = np.argmax(array)
print("max", max_value)
print(position)

max 47
3


In [15]:
sorted_array = np.sort(array)[::-1]
print(sorted_array)

[47 40 39 38 36 34 33 31 30 30 28 27 24 23 12 12 11  8  3  3]


### Завдання 2
* Запитайте в користувача верхню та нижню межу діапазону чисел.
* Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
* Виведіть вихідну матрицю.
* Отримайте головну діагональ і виведіть діагональні елементи.
* Підрахуйте суму елементів головної діагоналі та виведіть результат.
* Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [16]:
low = int(input(""))
high = int(input(""))

 1
 2


In [18]:
matrix = np.random.randint(low, high + 1, size=(5, 5))
print(matrix)

[[1 2 2 1 1]
 [1 1 2 1 2]
 [2 1 1 1 1]
 [2 1 2 1 2]
 [2 2 1 2 2]]


In [19]:
diag = np.diag(matrix)
print(diag)

[1 1 1 1 2]


In [20]:
diag_sum = np.sum(diag)
print(diag_sum)

6


In [26]:
for i in range(5):
    for j in range(5):
        if j > i:   
            matrix[i][j] = 0

In [27]:
print(matrix)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [2 1 1 0 0]
 [2 1 2 1 0]
 [2 2 1 2 2]]


### Завдання 3
* Запитайте у користувача початок і кінець діапазону чисел.
* Сформуйте послідовність цілих чисел у вказаному діапазоні.
* Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
* Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
* Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [28]:
start = int(input(""))
end = int(input(""))

 5
 7


In [32]:
guk = np.arange(start, start + 30) 

In [34]:
matrix = guk.reshape(6, 5)

In [35]:
print(matrix)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


In [37]:
row_sums = np.sum(matrix, axis=1)
print(row_sums)

[ 35  60  85 110 135 160]


In [38]:
col_max = np.max(matrix, axis=0)
print(col_max)

[30 31 32 33 34]


### Завдання 4
* Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
* Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
* Виведіть вихідний масив.
* Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
* Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
* Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.

In [39]:
low = int(input(""))
high = int(input(""))

 5
 10


In [40]:
array = np.random.randint(low, high + 1, 15)

In [41]:
print(array)

[ 7  7  9 10 10  8  6  9  5  7  9  8  8  8  6]


In [42]:
negative = array[array < 0]
print(negative)

[]


In [43]:
modified = array.copy()
modified[modified < 0] = 0

In [44]:
print(modified)

[ 7  7  9 10 10  8  6  9  5  7  9  8  8  8  6]


In [46]:
zero_count = np.sum(modified == 0)
print( zero_count)

0


### Завдання 5
* Запитайте в користувача довжину масивів.
* Створіть два одновимірні масиви вказаної довжини:
* перший заповніть випадковими числами від 0 до 10;
* другий заповніть випадковими числами від 10 до 20.
* Виведіть обидва вихідні масиви.
* Об'єднайте масиви в один і виведіть результат.
* Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.

In [47]:
n = int(input(""))

 11


In [48]:
array1 = np.random.randint(0, 11, n)
array2 = np.random.randint(10, 21, n)

In [49]:
print(array1)


[3 0 4 9 2 4 8 4 3 5 7]


In [50]:
print(array2)

[19 10 19 18 19 14 16 17 17 17 10]


In [51]:
combined = np.concatenate((array1, array2))
print(combined)

[ 3  0  4  9  2  4  8  4  3  5  7 19 10 19 18 19 14 16 17 17 17 10]


In [52]:
sum_array = array1 + array2
diff_array = array1 - array2

In [53]:
print(sum_array)


[22 10 23 27 21 18 24 21 20 22 17]


In [54]:
print(diff_array)

[-16 -10 -15  -9 -17 -10  -8 -13 -14 -12  -3]


### Завдання 6
* Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
* творіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
* Виведіть вихідну матрицю.
* Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
* Виведіть отриману матрицю.
* Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
* ідрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [70]:
rows = int(input(""))
cols = int(input(""))


 5
 5


In [72]:
matrix1 = np.arange(1, rows * cols + 1).reshape(rows, cols)

In [73]:
print(matrix1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [74]:
new_rows = int(input(" ")) 
new_cols = int(input(" "))

  5
  5


In [75]:
matrix2 = np.random.randint(0, 10, size=(new_rows, new_cols))

In [76]:
print (matrix2)

[[0 1 3 7 6]
 [6 1 2 7 0]
 [5 6 3 2 9]
 [6 0 2 1 7]
 [5 8 3 8 5]]


In [77]:

com = matrix1 + matrix2


In [78]:
print (com)

[[ 1  3  6 11 11]
 [12  8 10 16 10]
 [16 18 16 16 24]
 [22 17 20 20 27]
 [26 30 26 32 30]]
